### PR TITLE
Add ability to create a feature in the UI

### PR DESCRIPTION
**Pull request by midu**
## [Bring back ruby 1.8.7 compatibility](https://github.com/midu/rollout_ui/commit/793e82cc1a19b04ddf0f150e15ff098e11576cfa#L1R18)

`Rollout 1.1.0` is not compatible with `ruby 1.8.7` and most of the code in `rollout_ui` does not take advantages of the changes brought by `1.1.0` so I took the liberty allowing the previous version.

(tests pass on both versions)
## [Feature#percentage returns 0](https://github.com/midu/rollout_ui/commit/acf8d7bf309330e649aac8f70b6b2f54c79bd060#L0R13)

Because `nil` and `0`% mean the same thing (here).
## [Remove ActiveRecord from the dummy app](https://github.com/midu/rollout_ui/commit/d8b1b6f93a834fbf5506b0b51c80c2f472ca6471#L0L3)

So no database is needed for testing
## Allow creation of a feature via Rollout UI

This is the main reason for this fork.

We needed a strategy to add a feature in rollout before pushing it from dev to prod (or other environments).

The choices were some rake task to run on deploy or adding the functionality to rollout ui. The latter allows non(-too)-tech people to do it as well and prevents having to ssh onto a server or deploy an app just to create a redis key.

The newly created feature is activated for no one.

It's definitely not as pretty as it could be but this is where my designer skills stop.

### CODE REVIEW

**Comment by midu** [comment]
(note: these commits were paired with @kevinbongart)

**Comment by jrallison** [comment]
I'm a bit confused.  Why is it needed to add a feature to an environment before deploy?

If the feature isn't added, it seems like it should behave cleanly:
- Deploy
- Feature is off as it doesn't exist in redis
- Turn feature on in RolloutUI
- Feature is on

Can you help me understand the use case for needing to populate redis prior to the deploy?

**Comment by jrallison** [comment]
Also, I'd prefer not to downgrade Rollout.  What isn't compatible with ruby 1.8.7 in rollout 1.1?  That may be an issue to fix in rollout itself.

**Comment by midu** [comment]
Well, the use case we have is this:

we will only hit a rollout.active?(:feature) after doing something a bit long to do (on staging) and that we can not do on production (eg: publish a challenge)

Until then, the feature key won't be in redis which means it won't be in rollout ui, which is a little bit problematic.

**Comment by jrallison** [comment]
Ah, I see.  I get it now.  Thanks.

**Comment by jrallison** [comment]
And the design maintainer for the UI is Holly, so she may be able to help. :)

**Comment by midu** [comment]
for the rollout version part, you're right. I'll see what I can do about it tomorrow

**Comment by returntrue** [comment]
Hey @jrallison I think we are waiting on you to accept this pull request.  No rush, just FYI :)

**Comment by midu** [comment]
@returntrue we're working on some issues on other pull requests

**Comment by returntrue** [comment]
OK fine I take it back

**Comment by jrallison** [comment]
Any word from Holly on design?

**Comment by KevinBongart** [comment]
Holly and I paired to make it look better. A pull request is open [on Stefano's repo](http://github.com/midu/rollout_ui/pull/1) but still needs some love.

**Comment by cmer** [comment]
+1

**Comment by andrewhao** [comment]
+1. Any status on this?

**Pull request closed without merging**
